# Devise Override Controller
class SessionsController < Devise::SessionsController
  layout 'marketing', only: [:new, :create]

  def validate_otp
    if current_user.validate_otp_token(params[:user][:token].gsub(/\D/, ''))
      current_user.update(otp_enabled: true, otp_enabled_on: Time.now)
    else
      flash[:alert] = "Invalid token. It should be a 6 digit number generated by the app you scanned the QR code with."
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def check_captcha
    # Build the resource BEFORE the captcha check so the error message we add
    # below actually attaches to something the view renders, and so the form
    # re-renders with the email the user already typed.
    self.resource = resource_class.new(sign_in_params)
    return true if valid_captcha?

    resource.errors.add(:base, "Couldn't verify that you're a human. Please complete the captcha below and try again.")
    flash.now[:alert] = "Captcha verification failed. Please try again."
    respond_with_navigational(resource) { render :new }
  end
end
