# Devise Override Controller
class SessionsController < Devise::SessionsController
  layout 'marketing', only: [:new, :create]
  prepend_before_action :check_captcha, only: [:create]

  def validate_otp
    if current_user.validate_otp_token(params[:user][:token].gsub(/\D/, ''))
      current_user.update(otp_enabled: true, otp_enabled_on: Time.now)
    else
      flash[:alert] = "Invalid token. It should be a 6 digit number generated by the app you scanned the QR code with."
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def check_captcha
    if valid_captcha?(model: resource)
      true
    else
      self.resource = resource_class.new sign_in_params
      respond_with_navigational(resource) { render :new }
    end
  end
end
